### PR TITLE
🔀 v0.1.5

### PR DESCRIPTION
**Pull request by AA-Turner**
- Add support for Conda
- Adopt Black, the uncompromising code formatter
- Adjust build process for PEP 517 & 518 compliance
- Add more documentation

Note - setup.py could be removed at this point, but has not been to still support editable installs. However I don't know if that is still worth the (potential) confusion, and removing setup.py would clean up the top-level namespace

### CODE REVIEW

**Comment by rglss** [comment]
On compass/people.py - from memory I altered the people scraper as was encountering exceptions within the xpath queries. This was occurring when Compass permissions weren't rendering fields (i.e. Religion). Added in the __extract_details method to catch and handle any xpath error when scraping. Can't recall exactly why as from memory thought xpath would fail safely if the element doesn't exist. Will retest this and check.

**Comment by AA-Turner** [comment]
I thought it would be something like that, but couldn't reproduce errors my end. I'd prefer to add limited try/except clauses to specific fields -- as it points out areas explicitly (& fewer function calls, which are slowish in CPython!)

**Comment by AA-Turner** [comment]
Testing in general will be quite interesting -- I have been avoiding it for now, as any 'proper' testing suite would involve all possible permissions groups etc etc. I think perhaps useful though where errors have occured to save the response.content str (bytes), and with redaction of data we could use these in some form?

**Comment by rglss** [comment]
From looking at all the data we have, I think it's never safe to assume a field will be present. There's been multiple occasions that 'core' fields (email/address etc) are missing within the Compass record. What I can't remember is why these were generating exceptions, as by way of design XPath should just return None if it doesn't match...

**Comment by rglss** [comment]
Don't think this is directly related, but this now errors if the crawler doesn't get a DOB or Join Date: ParserError: String does not contain a date (i.e. empty string or None returned from xpath)

New pull request incoming...

**Comment by AA-Turner** [comment]
Brill - I use this on an Administrator role so if those fields don't show up on other roles then good to catch.

Longer term, we should validate permission levels and what we **expect** to see. 

I.e. seperating the input / data errors from Compass and errors caused by the library (e.g. if field order breaks a lot of the parsing will break -- if we suppress errors generally this will be hard(er) to spot!

**Comment by rglss** [comment]
Yer - I've also seen 'Unknown' for join dates so handle that case.

That would be nice, these are inherent issues with scraping data from webpages. Long term it'll turn into a game of cat and mouse as the Compass system evolves..!

**Pull request merged**
